name: Publish package

on:
  push:
    branches:
      - develop

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    uses: dvsa/des-workflow-actions/.github/workflows/publish-package.yaml@main
    with:
      WORKING_DIRECTORY: '.'
      PACKAGE_NAME: '@dvsa/mes-microservice-common'
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
